GET http://localhost:3000

###fetch all songs
GET  http://localhost:3000/songs

###fetch a single song
GET  http://localhost:3000/songs/1

###create new songs
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "first song with dto",
    "artists": "dfgfg",
    "releaseDate": "2024-04-03",
    "duration": "02:50"
}

###update a songs
PUT http://localhost:3000/songs/1

###delete a songs
DELETE http://localhost:3000/songs/1